name: api-pydolarvenezuela

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "It2CQpKaTP6QZkq-ZA5mSw"
    networks:
      - pydolar

  db:
    image: "postgres:alpine"
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 95NGmk2jG5p5ZzKkrBC4Ng
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    networks:
      - pydolar

  web:
    container_name: web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - path: .env
        required: true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - pydolar
#    volumes:
#      - ..:/app

#volumes:
#  db:

networks:
  pydolar:
    name: pydolar
